version: "3"
services:
  mongo:
    container_name: mongo-server
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  api:
    container_name: api-container
    build: ./server
    image: api-server
    command: npm start
    volumes:
      - ./dist:/usr/api/dist
    ports:
      - "3001:3001"
    links:
      - mongo
    depends_on:
      - mongo

  socket:
    container_name: socket-container
    build: ./socket
    image: socket-server
    command: npm start
    ports:
      - "3002:3002"

  client:
    container_name: client-container
    build: ./client
    image: client-server
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - api
      - socket